// Tests for the integration-assertion verifier (RFC 7523; RS256 + ES256 against an
// imported PEM public key). Vectors are generated by PyJWT/cryptography (see the
// generator in the commit) with a far-future exp so `now_epoch` can be pinned.
#include <gtest/gtest.h>
#include "assertion_verify.h"

using httpbridge::IntegrationClaims;
using httpbridge::verifyIntegrationAssertion;

namespace {

static const char* RSA_PUB_PEM =
    "-----BEGIN PUBLIC KEY-----\n"
    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApbY7JvGnXbo/ID8Z9fia\n"
    "DW9kO0WehNDloAdiChs1zX9Nd8j0f6KyrPlS39cUvPuIYgIEJ90k3SPIHLUFOT/J\n"
    "TixdFrMbhdjMTHIfisUAMK3b14CE+x5DUoVkamdCDrlb3DdrH+Zjmm8+JJRnPjW1\n"
    "mo9COWcprezC8NDdAMm8loxbvfBllxde2tbQoROc13wNtN3GUgg+oE/KD1EhnYmr\n"
    "Luuw0pSvlNvNb1DnAVuqwbV3i2KLOXKoTmpD5/L+6F+VGOw50+8s3JQGbChU8CRO\n"
    "YzMI2ZXgz8BuUbU6nbn+N318GGTIdBV2PL5YG4wSfs02U/6c/S2Ul3uDyTjXMe7n\n"
    "vQIDAQAB\n"
    "-----END PUBLIC KEY-----\n";
static const char* EC_PUB_PEM =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE98KmIi28GYyxbVm4JkO2c0Is+Yj4\n"
    "ZiekGCikzhV2tpo2sWYp7M6ryh7rtRCOMANh5RVI4spJ5Cog0o2uOc3X5Q==\n"
    "-----END PUBLIC KEY-----\n";
static const char* RS256_ASSERTION =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhY21lLWludGVncmF0aW9uIiwic3ViIjoiYWxpY2VAYWNtZSIsImF"
    "1ZCI6Imh0dHBzOi8vZmlsZXMuZXhhbXBsZS5jb20vdjEvYXV0aC9leGNoYW5nZSIsImV4cCI6MjAwMDAwMDAwMCwiaWF0IjoxNzA"
    "wMDAwMDAwLCJqdGkiOiJhc3NlcnQtMDAwMSIsInRlbmFudCI6ImFjbWUiLCJzY29wZSI6ImZpbGVzLnJlYWQgZmlsZXMud3JpdGU"
    "iLCJ0b2tlbl90eXBlIjoiZGVsZWdhdGVkIn0.JOWidEYo4vMD4f6t2zlEDGDHDzMTqGy8zoXOmgaxzUjdGk3KBhs0Z_3nGrW0qqB"
    "g0GGHEyDOKlylVtE_Rryi9QG5tSdmnhVsdtE-PeNTWqVu_n4XG3Z0tJM_ZGeuG3EWdtc3gVNp1WUpPk5MiuHktKUj7auE6NHHZEO"
    "xNX1IfdjzWOoaQpqUioBt0n_-N5iZ0Q0nynl4X07NOfM4PaDStURYF0cKH-jxojWrczpIQxEM9nNjIJh1k39b8lG_4SIXw4RjYOs"
    "3nCA8HROZeqySzXjqLDsIV5m6HdiRRRBM2mG4ibxfTSjhv2e0FPfnO5bPLTg0FVd4IQQqKxFlyq6GCg";
static const char* ES256_ASSERTION =
    "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhY21lLWludGVncmF0aW9uIiwic3ViIjoiYWxpY2VAYWNtZSIsImF"
    "1ZCI6Imh0dHBzOi8vZmlsZXMuZXhhbXBsZS5jb20vdjEvYXV0aC9leGNoYW5nZSIsImV4cCI6MjAwMDAwMDAwMCwiaWF0IjoxNzA"
    "wMDAwMDAwLCJqdGkiOiJhc3NlcnQtMDAwMSIsInRlbmFudCI6ImFjbWUiLCJzY29wZSI6ImZpbGVzLnJlYWQgZmlsZXMud3JpdGU"
    "iLCJ0b2tlbl90eXBlIjoiZGVsZWdhdGVkIn0.bGz0hSlsOX-VdOgkMKH2t77P1STnspXT8hmiTqfP6kXL5Pwvp6Uxy62Nz2UU3kn"
    "t9b4z2ullpEgqtRZdjC_WbQ";

const char* ISS = "acme-integration";
const char* AUD = "https://files.example.com/v1/auth/exchange";
const long PAST = 1700000100;  // just after iat, far before exp

}  // namespace

TEST(AssertionVerify, RS256HappyPath) {
    IntegrationClaims c; std::string err;
    ASSERT_TRUE(verifyIntegrationAssertion(RS256_ASSERTION, ISS, AUD, RSA_PUB_PEM, c, err, PAST)) << err;
    EXPECT_EQ(c.issuer, "acme-integration");
    EXPECT_EQ(c.subject, "alice@acme");
    EXPECT_EQ(c.tenant, "acme");
    EXPECT_EQ(c.scope, "files.read files.write");
    EXPECT_EQ(c.jti, "assert-0001");
    EXPECT_EQ(c.token_type, "delegated");
    EXPECT_EQ(c.expires_at, 2000000000L);
}

TEST(AssertionVerify, ES256HappyPath) {
    IntegrationClaims c; std::string err;
    ASSERT_TRUE(verifyIntegrationAssertion(ES256_ASSERTION, ISS, AUD, EC_PUB_PEM, c, err, PAST)) << err;
    EXPECT_EQ(c.subject, "alice@acme");
    EXPECT_EQ(c.tenant, "acme");
}

TEST(AssertionVerify, WrongKeyRejected) {
    IntegrationClaims c; std::string err;
    // Verify an RS256 assertion against the EC key (and vice versa) — must fail.
    EXPECT_FALSE(verifyIntegrationAssertion(RS256_ASSERTION, ISS, AUD, EC_PUB_PEM, c, err, PAST));
    EXPECT_FALSE(verifyIntegrationAssertion(ES256_ASSERTION, ISS, AUD, RSA_PUB_PEM, c, err, PAST));
}

TEST(AssertionVerify, TamperedPayloadRejected) {
    // Flip a character in the payload segment; the signature no longer matches.
    std::string t = RS256_ASSERTION;
    const size_t dot1 = t.find('.');
    t[dot1 + 5] = (t[dot1 + 5] == 'A' ? 'B' : 'A');
    IntegrationClaims c; std::string err;
    EXPECT_FALSE(verifyIntegrationAssertion(t, ISS, AUD, RSA_PUB_PEM, c, err, PAST));
}

TEST(AssertionVerify, IssuerMismatchRejected) {
    IntegrationClaims c; std::string err;
    EXPECT_FALSE(verifyIntegrationAssertion(RS256_ASSERTION, "other-integration", AUD, RSA_PUB_PEM, c, err, PAST));
    EXPECT_EQ(err, "assertion issuer mismatch");
}

TEST(AssertionVerify, AudienceMismatchRejected) {
    IntegrationClaims c; std::string err;
    EXPECT_FALSE(verifyIntegrationAssertion(RS256_ASSERTION, ISS, "https://evil.example.com", RSA_PUB_PEM, c, err, PAST));
    EXPECT_EQ(err, "assertion audience mismatch");
}

TEST(AssertionVerify, ExpiredRejected) {
    IntegrationClaims c; std::string err;
    // now well past exp (2000000000) + leeway.
    EXPECT_FALSE(verifyIntegrationAssertion(RS256_ASSERTION, ISS, AUD, RSA_PUB_PEM, c, err, 2000001000L));
    EXPECT_EQ(err, "assertion expired");
}

TEST(AssertionVerify, MalformedRejected) {
    IntegrationClaims c; std::string err;
    EXPECT_FALSE(verifyIntegrationAssertion("not-a-jwt", ISS, AUD, RSA_PUB_PEM, c, err, PAST));
    EXPECT_FALSE(verifyIntegrationAssertion("a.b", ISS, AUD, RSA_PUB_PEM, c, err, PAST));
}

TEST(AssertionVerify, NoneAlgRejected) {
    // alg:none header, empty signature — classic downgrade attack, must be refused.
    // header {"alg":"none","typ":"JWT"} . <same payload> .
    std::string none_hdr = "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0";
    std::string payload = std::string(RS256_ASSERTION);
    const size_t d1 = payload.find('.'), d2 = payload.find('.', d1 + 1);
    std::string body = payload.substr(d1 + 1, d2 - d1 - 1);
    std::string orig_sig = payload.substr(d2 + 1);
    // Keep a (now-meaningless) signature so the token is a well-formed 3-part JWT and
    // the alg:none guard — not the malformed check — is what rejects it.
    std::string forged = none_hdr + "." + body + "." + orig_sig;
    IntegrationClaims c; std::string err;
    EXPECT_FALSE(verifyIntegrationAssertion(forged, ISS, AUD, RSA_PUB_PEM, c, err, PAST));
    EXPECT_EQ(err, "unsupported assertion alg (expected RS256 or ES256)");
}

TEST(AssertionVerify, EmptyPemRejected) {
    IntegrationClaims c; std::string err;
    EXPECT_FALSE(verifyIntegrationAssertion(RS256_ASSERTION, ISS, AUD, "", c, err, PAST));
}
