// OIDC id_token verification tests. Fixtures (a real RS256 id_token + its JWKS)
// are generated by the Python snippet in the commit message; do not hand-edit the
// long strings below — regenerate them if the fixture generator changes.
#include "oidc_verify.h"

#include <gtest/gtest.h>
#include <string>

using httpbridge::IdTokenClaims;
using httpbridge::verifyIdToken;

namespace {

const std::string kJwks = R"JSON({"keys": [{"kty": "RSA", "use": "sig", "alg": "RS256", "kid": "test-key-1", "n": "vNzOZVZ1Z_wMlvBHnGR3VMuGYzT_MeIcxJZBi23sJCkm-4UH-j8WYD5tnhjJgLQlEPA96vEoryxcDZaC_eNMQiMuEkkfRrc8Exh0Tixl0UPTiNj_yr2BGa7FzEqVrZlRqzNQbL1jnaovSHbvkQg2IfFsrm12pBCI22cP4Niztki66A775-rbRyZwxB1IQyEZy6s6wu5A-51G9D-iTfCaBQjOV158n5m8zggHnWUFn9gxHVjyTghx2nfwblT0M8YcTpOJm7QApw3Ni9mzvxhc3eerqF1UZ46fddJZzCbUhMGr3kYKEojWgYOMWps0Y2fvUfsbYic2v_sJf7Q1CdxLuQ", "e": "AQAB"}]})JSON";
const std::string kIdToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6InRlc3Qta2V5LTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2lkcC5leGFtcGxlLmNvbSIsImF1ZCI6ImNsaWVudC1hYmMiLCJzdWIiOiJpZHAtc3ViamVjdC00MiIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibm9uY2UiOiJub25jZS14eXoiLCJpYXQiOjE4MDAwMDAwMDAsImV4cCI6MTgwMDAwMzYwMH0.RQzAWw5ufNjVPN83jEfl1Tv5hnG5jlJXJQxfVUuoUD-HkNNC8_gxdsGxhkpnh3aF9-3sqruVb-Z0FKA0a-Wr1GLVoxC8hdAtGwYUSYPRVh-CcjUbLvfe8fRUGSyhAWVQS0ch4ZUuveFCAimyVyIKhSKsdsW1XW0fKx97bAjkt22K6a7wmn4bTSVbG5eCWKePdXLGYJy20qunSQN5sfBfuSTNko3jE4mRgxvTXpfdIClnlEvL_WsXpOAIKH7c4tO3qtYyc7oO9unddX3Cynid-zfJ9uug9TCGFLeVT2EGztdgpdEOYbwy0dkkuTjjye6PRDW9hIfvu7OamuV1YJJWOg";
const std::string kIdTokenBadSig = "eyJhbGciOiJSUzI1NiIsImtpZCI6InRlc3Qta2V5LTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2lkcC5leGFtcGxlLmNvbSIsImF1ZCI6ImNsaWVudC1hYmMiLCJzdWIiOiJpZHAtc3ViamVjdC00MiIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibm9uY2UiOiJub25jZS14eXoiLCJpYXQiOjE4MDAwMDAwMDAsImV4cCI6MTgwMDAwMzYwMH0.taZZMnYqdxX1wtl_jcJIiqosxJZf9IUMTVy5YOT8YGcnSCkMS-uoCxGDkHe072fo4w6o_QX-VkxMSMXd-y81CAtadzfMAfIYNEAhwihdKqpbwx-0YFCj21tKvCAL6les742uQDA2o_EXSC9uEB7aMvR6HcoBca9SXznoutoNQ7PYweZDHwVvAkSP8nDIdnxdB9TpV_s1o_6BtF71o2dpNnxO8D8TNejkzK4lka_0FBcm-wpD7vjF5oveFlXhwZu0K09mMrPCCqdixBiUfOgNcTOJpmj9CyuY0jkLehp26H688dUs06uotOQ88D4tW_vao6FSlc2VkpOxUx4DwRqTvA";
const long kNow = 1800000000;  // exp = now+3600
// ISS=https://idp.example.com AUD=client-abc NONCE=nonce-xyz
const std::string kIssuer = "https://idp.example.com";
const std::string kAud = "client-abc";
const std::string kNonce = "nonce-xyz";

}  // namespace

TEST(OidcVerify, AcceptsAValidToken) {
    IdTokenClaims out; std::string err;
    ASSERT_TRUE(verifyIdToken(kIdToken, kIssuer, kAud, kNonce, kJwks, out, err, kNow)) << err;
    EXPECT_EQ(out.subject, "idp-subject-42");
    EXPECT_EQ(out.email, "alice@example.com");
    EXPECT_TRUE(out.email_verified);
}

TEST(OidcVerify, AcceptsWhenNoNonceExpected) {
    IdTokenClaims out; std::string err;
    EXPECT_TRUE(verifyIdToken(kIdToken, kIssuer, kAud, "", kJwks, out, err, kNow)) << err;
}

TEST(OidcVerify, RejectsWrongIssuer) {
    IdTokenClaims out; std::string err;
    EXPECT_FALSE(verifyIdToken(kIdToken, "https://evil", kAud, kNonce, kJwks, out, err, kNow));
    EXPECT_NE(err.find("issuer"), std::string::npos);
}

TEST(OidcVerify, RejectsWrongAudience) {
    IdTokenClaims out; std::string err;
    EXPECT_FALSE(verifyIdToken(kIdToken, kIssuer, "other-client", kNonce, kJwks, out, err, kNow));
    EXPECT_NE(err.find("audience"), std::string::npos);
}

TEST(OidcVerify, RejectsNonceMismatch) {
    IdTokenClaims out; std::string err;
    EXPECT_FALSE(verifyIdToken(kIdToken, kIssuer, kAud, "wrong-nonce", kJwks, out, err, kNow));
    EXPECT_NE(err.find("nonce"), std::string::npos);
}

TEST(OidcVerify, RejectsExpired) {
    IdTokenClaims out; std::string err;
    // now well past exp (kNow + 3600 + leeway)
    EXPECT_FALSE(verifyIdToken(kIdToken, kIssuer, kAud, kNonce, kJwks, out, err, kNow + 4000));
    EXPECT_NE(err.find("expired"), std::string::npos);
}

TEST(OidcVerify, RejectsBadSignature) {
    IdTokenClaims out; std::string err;
    // token signed by a different key than the one in the JWKS
    EXPECT_FALSE(verifyIdToken(kIdTokenBadSig, kIssuer, kAud, kNonce, kJwks, out, err, kNow));
    EXPECT_NE(err.find("signature"), std::string::npos);
}

TEST(OidcVerify, RejectsMalformedToken) {
    IdTokenClaims out; std::string err;
    EXPECT_FALSE(verifyIdToken("not-a-jwt", kIssuer, kAud, kNonce, kJwks, out, err, kNow));
    EXPECT_FALSE(verifyIdToken("a.b", kIssuer, kAud, kNonce, kJwks, out, err, kNow));
}

TEST(OidcVerify, RejectsKidNotInJwks) {
    IdTokenClaims out; std::string err;
    const std::string emptyJwks = R"({"keys":[]})";
    EXPECT_FALSE(verifyIdToken(kIdToken, kIssuer, kAud, kNonce, emptyJwks, out, err, kNow));
    EXPECT_NE(err.find("JWKS key"), std::string::npos);
}
